---
- name: Setup SAP HANA HSR
  hosts: all
  become: true
  any_errors_fatal: true
  vars:
    primary_site_name: dc1
    secondary_site_name: dc2

    #
    # SAP HANA HSR configuration
    #
    sap_ha_install_hana_hsr_sid: 'ABC'
    sap_ha_install_hana_hsr_instance_number: '123'
    # This should come from vault
    sap_ha_install_hana_hsr_db_system_password: 'Foobar_12'

    # These must be adjusted in case using a dedicated network
    sap_ha_install_hana_hsr_primary_ip: 192.168.122.10
    sap_ha_install_hana_hsr_primary_hostname: saphana1
    sap_ha_install_hana_hsr_secondary_ip: 192.168.122.20
    sap_ha_install_hana_hsr_secondary_hostname: saphana2
    sap_ha_install_hana_hsr_fqdn: example.com

    # These must be adjusted in case using a dedicated network 
    sap_ha_install_hana_hsr_alias: "{{ primary_site_name if inventory_hostname == sap_ha_install_hana_hsr_primary_hostname + '.' + sap_ha_install_hana_hsr_fqdn else secondary_site_name }}"
    sap_ha_install_hana_hsr_role: "{{ 'primary' if inventory_hostname == sap_ha_install_hana_hsr_primary_hostname + '.' + sap_ha_install_hana_hsr_fqdn else 'secondary' }}"

    sap_ha_install_hana_hsr_rep_mode: syncmem
    sap_ha_install_hana_hsr_oper_mode: logreplay
  roles:
    - sap_ha_install_hana_hsr
